{
 "title": "Drone dashboard",
 "time": { "from": "2022-09-13T12:49:00.000Z", "to": "2022-09-13T12:51:00.000Z" },
 "panels": [
  {
   "title": "VelocityZ",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"DJI_AIR_2S\"] == \"Basic_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"VelocityZ\")\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Dji\")\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "VelocityX",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"DJI_AIR_2S\"] == \"Basic_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"VelocityX\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "VelocityY",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Dji\")\n  |> filter(fn: (r) => r[\"DJI_AIR_2S\"] == \"Basic_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"VelocityY\")\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Battery_current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"DJI_AIR_2S\"] == \"Battery_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \" Battery_current\")\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n  "
    }
   ]
  },
  {
   "title": "Battery_percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Dji\")\n  |> filter(fn: (r) => r[\"DJI_AIR_2S\"] == \"Battery_metrics\")\n  |> filter(fn: (r) => r[\"DJI_AIR_2S\"] == \"Battery_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Battery_percentage\")\n\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Battery_voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"Dji\")\n  |> filter(fn: (r) => r[\"DJI_AIR_2S\"] == \"Battery_metrics\")\n  |> filter(fn: (r) => r[\"DJI_AIR_2S\"] == \"Battery_metrics\")\n  |> filter(fn: (r) => r[\"_field\"] == \"Battery_voltage\")\n  |> aggregateWindow(every: 1s, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")\n  "
    }
   ]
  }
 ]
}